### ISSUE TITLE
Is that what you looking for in the README ? 

### ISSUE THREAD

**Issue by troymaclure** [M3TIOR/pyside2-style-test#1]
[QssStylesheetEditor](https://github.com/hustlei/QssStylesheetEditor)

![Capture d’écran 2020-03-27 à 01 37 18](https://user-images.githubusercontent.com/20599429/77709553-c4432380-6fcb-11ea-8197-f5a00aecbce0.png)

**Comment by M3TIOR** [comment]
Yeah kinda. Really funny, that project was started after I made mine lol.

**Comment by M3TIOR** [comment]
Oh well. At least there's a product that's better than mine now
